handlers/event.js
serverless.yml

Add function to scan events by code

Event code scan

---

handlers/event.js
serverless.yml

Event userUpdate function for event checkin, registration, waitlist

Event userUpdate function

---

handlers/reg.js
handlers/registration.js
serverless.yml

- Create registrationtable functions to add/update entries
- Functions to get entries by studentID and by eventID
- Remove database creation from serverless to avoid deployment trying to create new DB tables in the future
- Hopefully fixed serverless deployment bug with cloudwatch logs: https://github.com/serverless/serverless/releases/tag/v1.6.0
Closes: #6

RegistrationTable Function

---

.travis.yml
config.dev.json
config.prod.json
handlers/event.js
handlers/registration.js
handlers/user.js
serverless.test.yml
serverless.yml

`serverless deploy` will deploy to our dev API
`serverless deploy --stage prod` will deploy to our prod API
Production has a different url and requires a header of `x-api-key`
closes #6

Serverless Dev Environment

---

.travis.yml
handlers/event.js
handlers/helpers.js
handlers/user.js

~~No idea if this works. I will test it out on staging using our new pipeline features as soon as this PR is opened.~~
Seems to work now
Implementation: Call get on the item id and check if it is empty. If it is not empty then call updateItem
closes #16

Disable update functions from creating new items

---

.gitignore
handlers/event.js
handlers/helpers.js
handlers/registration.js
handlers/user.js
serverless.test.yml
serverless.yml

Sorry this PR got kind of large due to the problems uncovered by tests that needed to be fixed.
Main changes:
-Added integration tests
-Performed checking for mandatory ID fields that serverless doesn't seem to check for (and thus they previously returned unhelpful error responses, see https://github.com/serverless/serverless/issues/5034)
-Other more helpful error messages added
-Removed uneeded updateStudent function in events
-Other code/comment style fixes 
Closes: #10

Integration tests and Improvements

---

.travis.yml
config.staging.json

note, staging environment will use the same databases as dev. The lambda functions will be different from dev though
I'm going to delete the dev branch in this repo once this gets merged

Setup a staging environment

---

serverless.yml

It worked on dev. Hopefully it works on Prod too hahaha! 🤞 
If this works, `biztechApp-prod-us-west-2-lambdaRole` should have access to biztechUsersPROD etc
closes #22

Fix prod DB access

---

handlers/event.js
package-lock.json
serverless.test.yml

Add some more info and rename some variables based on the way data is sent by bt-web
Also generate the event sign in code in the backend instead of frontend
Closes #13

Event create

---

handlers/event.js
handlers/helpers.js
serverless.test.yml
serverless.yml

A function that returns an array of user data for users going to the event specified
Had to update node version to support `.flatMap()`
Closes #31

Add events/getUsers

---

handlers/default.js
handlers/event.js
handlers/helpers.js
handlers/registration.js
handlers/user.js

- new helper function createResponse to easily create a response object
- Add `Access-Control-Allow-Headers` to response headers
closes #37

createResponse helper

---

.travis.yml
handlers/default.js
handlers/event.js
handlers/helpers.js
handlers/registration.js
handlers/user.js

(pushes to master deploy to staging, pushes to prod deploy to prod)

Deploy Prod

---

handlers/event.js

Rename location field, also ran prettier on the file

Rename location field

---

handlers/event.js

Was causing errors in prod because we were looking at the wrong table in prod

Append environment to tablename in event/UsersGet

---

handlers/event.js
serverless.yml
utils/sorters.js

I looked up DynamoDB sort and hash keys and spent a bit of time fiddling around with it - I couldn't really get it working and a lot of online opinion suggest that 'ordering' the data when querying from DynamoDB isn't usually a recommended pattern somehow?
- During testing I had some trouble getting the users of an event, so I included a quick fix that seems to get it working so far.  I added some comments to clarify!
- Also included changes to `serverless.yml` to adapt to the shift in using the dev@ubcbiztech.com serverless account
❗I think an update to travis CI's `SERVERLESS_ACCESS_KEY` is required for the general repo (I added a termporary access key specific to this branch)
Closes #38
Closes #51

Sort query

---

handlers/registration.js
package-lock.json
package.json
serverless.yml

- added SendGrid API key to Serverless and Travis
- Implemented method that sends a dynamic email to users when registration is created to inform them whether they have been i) registered or ii) waitlisted
- SendGrid template is https://app.sendgrid.com/login?redirect_to=%2F if anyone wants to edit it or take a look

Registration emails

---

handlers/registration.js
package-lock.json
package.json
serverless.test.yml

Include heardfrom in registration create

---

.github/workflows/deploy-prod.yml
.github/workflows/deploy.yml
scripts/resetMemberships.js

Closes #
👷 **Changes:**
💭 **Notes:**

Fix deploy

---

services/registrations/handler.js

çrter This is Git's per-user configuration file.
[user]
[user]
Closes #
👷 **Changes:**
filter partners in query for registrations
💭 **Notes:**

Filter partners

---

services/events/handler.js
services/members/test/memberGet.js
services/payments/handler.js
services/qr/helpers.js
services/registrations/handler.js
services/registrations/test_integration/registration.js
services/teams/handler.js
services/teams/helpers.js
services/users/handler.js
services/users/test/userGet.js

Closes #
👷 **Changes:**
💭 **Notes:**

deploy eslint fixes to prod

---

scripts/resetMemberships.js
services/events/handler.js
services/events/helpers.js
services/registrations/handler.js
services/registrations/helpers.js

Closes # https://www.notion.so/ubcbiztech/b24732925a6745caa305a2c746fa5ba7?v=d557178d0a134acf85a3890882538364&p=7ba1e1b3691f49fcb097cab02fda54d9&pm=s
👷 **Changes:**
*Found workshop selection questions (with caps)
*Counted current registrations for each workshop, cap, and sent information.
*Changed some syntax to make calls from frontend easier. 
💭 **Notes:**
*Should be tested with frontend - [GitHub - ubc-biztech/bt-web at workshop-max-attendees](https://github.com/ubc-biztech/bt-web/tree/workshop-max-attendees)

Workshop cap

---

.github/workflows/deploy-prod.yml
.github/workflows/deploy.yml

Closes #
👷 **Changes:**
💭 **Notes:**

Upgrade node

---

.github/workflows/deploy.yml

Closes #
👷 **Changes:**
💭 **Notes:**

Add env o params

---

services/payments/handler.js

Closes #
👷 **Changes:**
💭 **Notes:**

changed function to await

---

services/registrations/handler.js
services/registrations/helpers.js

Closes # INTERIM soln for https://www.notion.so/ubcbiztech/b24732925a6745caa305a2c746fa5ba7?v=d557178d0a134acf85a3890882538364&p=b43039995bec41b3b3e7f4eeae26acd2&pm=s
👷 **Changes:**
Removes the .ics from the partner reg confirmation email.
The long term goal for this ticket still remains in that partners should only be sent a singular email, rather than two emails.
PICTURE: Shows that there is no .ics attachment for partner registrations
💭 **Notes:**

removed the .ics attachment for partner registration confirmation emails

---

services/registrations/handler.js

Closes # https://www.notion.so/ubcbiztech/b24732925a6745caa305a2c746fa5ba7?v=d557178d0a134acf85a3890882538364&p=f2f9d527942547818b4b35459b33903a&pm=s
👷 **Changes:**
removes emails to partners on registration of an event
💭 **Notes:**
linked to frontend change: https://github.com/ubc-biztech/bt-web/pull/494
+ this is merging into allan's branch

removed partner confirmation email on registration

---

services/qr/handler.js
services/registrations/EmailService/SESEmailService.js

Closes #
👷 **Changes:**
no pass env variables when not local
💭 **Notes:**

Email Service test bug fix

---

services/registrations/handler.js

Closes #
👷 **Changes:**
💭 **Notes:**

fixed leaderboard response

---

services/qr/helpers.js

Closes #
👷 **Changes:**
💭 **Notes:**

fixed event table

---

.github/workflows/deploy-prod.yml

Closes #
👷 **Changes:**
💭 **Notes:**

retrigger actions

---

services/qr/helpers.js

Closes #
👷 **Changes:**
💭 **Notes:**

fixed qr bug

---

services/payments/handler.js

Closes #
👷 **Changes:**
💭 **Notes:**

changed expiration

---

services/registrations/handler.js

Closes #
👷 **Changes:**
💭 **Notes:**

fixed lowercase emails

---

.github/workflows/deploy-prod.yml
.github/workflows/deploy.yml
services/payments/handler.js
services/payments/serverless.yml

Closes #
👷 **Changes:**
💭 **Notes:**

moved to env vars

---

package-lock.json
services/events/package-lock.json
services/hello/package-lock.json
services/members/handler.js
services/members/package-lock.json
services/members/serverless.yml
services/payments/package-lock.json
services/prizes/package-lock.json
services/qr/package-lock.json
services/registrations/handler.js
services/registrations/package-lock.json
services/registrations/serverless.yml
services/stickers/package-lock.json
services/teams/package-lock.json
services/transactions/package-lock.json
services/users/package-lock.json

Closes #
👷 **Changes:**
New massUpdate function. Uses the existing updateHelper.
Also had to create getFnameById since updateHelper requires fname to update. Modal takes in a bunch of emails but we needed to get fnames as well.
💭 **Notes:**
Not sure if getFnameById is out of place or bad design. I put it in /members. Now there's a get, getAll, and getFname.

Mass update status

---

services/payments/handler.js
services/users/handler.js
services/users/serverless.yml

Closes #
👷 **Changes:**
New check membership endpoint for unauthenticated calls to api.
💭 **Notes:**

Check membership

---

services/registrations/EmailService/SESEmailService.js
services/registrations/EmailService/templates/calendarInviteTemplates.js
services/registrations/EmailService/templates/dynamicQRTemplates.js
services/registrations/handler.js

Closes #
👷 **Changes:**
If application type event, it sends a payment processed link upon registration. Initial email regarding status is also changed to include a link to companion.
💭 **Notes:**

updated email flow for application process

---

services/registrations/EmailService/SESEmailService.js
services/registrations/EmailService/templates/calendarInviteTemplates.js
services/registrations/EmailService/templates/dynamicQRTemplates.js
services/registrations/handler.js

Closes #
👷 **Changes:**
💭 **Notes:**

updated email flow for application process (#349)

---

.github/workflows/deploy-prod.yml
.github/workflows/deploy.yml

Closes #
👷 **Changes:**
💭 **Notes:**

legpeerdeps

---

.github/workflows/deploy.yml

Closes #
👷 **Changes:**
💭 **Notes:**

remove cli options

---

package-lock.json
package.json

Closes #
👷 **Changes:**
💭 **Notes:**

install sdk

---

.github/workflows/deploy-prod.yml
.github/workflows/deploy.yml

Closes #
👷 **Changes:**
💭 **Notes:**

added node env var

---

services/events/handler.js

Closes #
👷 **Changes:**
Changed events getAll to query latest four months of events instead of all to speed up query.
💭 **Notes:**

changed to pull latest 4 months of events

---

lib/db.js
services/events/handler.js
services/members/handler.js
services/members/serverless.yml
services/payments/handler.js
services/qr/handler.js
services/registrations/EmailService/SESEmailService.js
services/registrations/handler.js
services/teams/helpers.js
services/users/handler.js

Closes #
👷 **Changes:**
- Went through all services to fix all dynamo db calls/
- tested most endpoints locally except for faved events lol
💭 **Notes:**
- Still needs additional testing in dev environment – should smoke test it

Service fixes

---

services/registrations/serverless.yml

Closes #
👷 **Changes:**
💭 **Notes:**

Fix email permissions for SES

---

services/registrations/EmailService/SESEmailService.js
services/registrations/EmailService/templates/dynamicQRTemplates.js

Closes #
👷 **Changes:**
💭 **Notes:**

Improve QR code attachment visibility and update registration email template

---

lib/snsHelper.js
package-lock.json
package.json
services/payments/handler.js
services/payments/package-lock.json
services/payments/package.json
services/payments/serverless.yml
services/registrations/EmailService/templates/dynamicQRTemplates.js
services/registrations/handler.js
services/registrations/package-lock.json
services/registrations/package.json
services/registrations/serverless.yml

Closes #
👷 **Changes:**
💭 **Notes:**

Update email message if QR code doesn't display; add SNS topic for monitoring

---

services/payments/handler.js
services/payments/serverless.yml

Partial reverts commit fc53d328445406f7bee61efefdaf6e2b83d1dfc6
Broke the Github Action deploy, but wasn't surfaced as a failing deployment:  https://github.com/ubc-biztech/serverless-biztechapp/actions/runs/10656864766/job/29536000335#step:6:157

Revert breaking .yml and SNS notifications for /payments services

---

services/stickers/handler.js
services/stickers/helpers.js
services/stickers/serverless.yml

Changes:
- created following endpoints
- getScores: returns all scores, now in a list with team name and corresponding score entires (/scores)
- getScoresRoom: filters by room (/scores/{roomID})
- getScoresTeam: filters by team (/scores/team/{teamName})
- getStickers: returns all stickers, in list with team name and corresponding stickers (/stickers)
- getStickersRoom: filters by room (/stickers/{roomID})
- GetStickersTeam: filters by team (/stickers/team/{teamName})
- roomID is now stored in both stickers and score table (we still expect that there should be no duplicate team names)
Notes:
- no bulk processing of data is done here, can do more if requested but otherwise will be handing off to marcus on frontend

Voting summary endpoints

---

lib/db.js
services/registrations/handler.js

Closes #
👷 **Changes:**
💭 **Notes:**

add createdAt field to registration (#398)

---

services/teams/handler.js
services/teams/helpers.js
services/teams/serverless.yml

👷 **Changes:**
I added an endpoint for updating the teams' points field through increments and decrements. 
💭 **Notes:**
It would potentially be beneficial to have an endpoint to set the points field, putting it on hold for the time sake of DataVerse. 

added endpoint to updated team's points

---

services/teams/helpers.js

👷 **Changes:**
Added so that final question adds a timestamp

added for timestamping the submission

---

lib/db.js
services/events/handler.js
services/events/serverless.yml
services/registrations/helpers.js

This PR introduces the use of a GSI (`event-overview`) on the Events table for the `getAll` endpoint to reduce the number of attributes projected during the SCAN operation, aiming to lower DynamoDB RCU usage. Lower RCU typically results in reduced AWS costs and improved latency.
- **Key Changes:**
- Use the `event-overview` GSI on the Events table with a reduced attribute set.
- Remove dependency on event counts from `getAll`.
- Remove the 4-month limit for viewing previous events; now, all events are shown. This has negligible impact on RCU and latency and was implemented per Jay's request.
As part of this change, event count attributes will no longer be added to each event returned by the `getAll` endpoint, as these are only needed for the `get` endpoint. Testing revealed that removing …

Events Service: Use GSI and remove event counts on getAll endpoint

---

services/qr/handler.js

Fixes minor bugs with QR handler
Closes #
👷 **Changes:**
- Changed db.scan to db.getOne 
-
💭 **Notes:**

Minor Bug Fixes to QR Handler

---

services/payments/handler.js
services/registrations/handler.js

Did some manual testing locally - merging to test with dev payments credentials for end-to-end check

Make registrations and payments case-insensitive

---

constants/tables.js
services/interactions/constants.js
services/interactions/handler.js
services/interactions/helpers.js
services/interactions/package-lock.json
services/interactions/package.json
services/interactions/serverless.yml
sls-multi-gateways.yml

👷 **Changes:**
- added interactions service
- bizConnections + bizQuests tables created
- uses queries and put commands based on LLD (see [here](https://www.notion.so/ubcbiztech/Workstream-B-Connections-Journal-and-Quests-169d13df991180ecad44c2004a6a12ca))
- relies on data in biztechQRs based on profile
- default get all connections returns in sorted order
💭 **Notes:**
- writes are done in individual Put Commands for development speed, ideally should be done with transaction writes to ensure atomicity, (rare race condition bug currently exists in code)

Interactions service - Journal Feature

---

services/interactions/serverless.yml

Small hotfix: Change requirement from querystring to path to maintain consistency between sls offline and actual deployment

Interactions deployment fix

---

scripts/generateNFCsForEventRegistrations.js
services/profiles/handler.js
services/profiles/package-lock.json
services/profiles/package.json
services/profiles/serverless.yml
services/profiles/test/profileTests.js

- Adds endpoints POST `/profiles` for instantiating Profiles based on Registration DB data, and GET `profiles/{profileID}`
- Creates DynamoDB with GSI in serverless.yml
- Adds (broken) unit tests
Manual testing on localhost. New unit tests aren't working, will figure out later

Create Profiles Service

---

.eslintrc.json
services/interactions/handler.js
services/interactions/helpers.js

- allow switch-case statements to have fallthrough (required for deployment integration)

Eslint Rule Update

---

constants/tables.js
services/interactions/handler.js
services/interactions/helpers.js
services/interactions/serverless.yml
services/profiles/handler.js
services/profiles/test/profileTests.js
services/stickers/handler.js

- Accommodated introduction of new profiles service and table -> modify all calls to QR table to profiles
- changed queries to directly use PK to reduce latency for get requests -> removed redundant calls to the profile table to get a user's original ID

Interactions profiles connection demo

---

services/interactions/handler.js
services/interactions/helpers.js

- removed redundant query to QRs table to accommodate move to profiles
- WORKSHOP_TWO id is somewhat obvious or something we may want to consider obfuscating since the quest is only for the challenge, wondering what best approach would be (obfuscate the workshop ID? authorization somehow? password?)

Fix: interactions, booths & workshops

---

services/profiles/handler.js
services/profiles/serverless.yml

- `createCompanyProfile` endpoint added
- `linkPartnerToCompany` endpoint added
Expediting merge to prod to unblock nametag creation
Manual testing

Add Delegates and Company profile creation endpoints

---

services/profiles/handler.js
services/profiles/serverless.yml

Going to prod directly for nametag creation

Add partial partner creation endpoint

---

services/profiles/handler.js

Merge to prod for nametag creation

Add pronouns to delegate profiles

---

scripts/generateQuestsForEventRegistrations.js
services/interactions/constants.js
services/interactions/handler.js
services/interactions/helpers.js
services/members/handler.js

- added quest workshop 2 1-on1 interview, and changed description
- added new logic for quests
- modified logic for handling interactions between execs and attendees
- fixed bug with partner interactions
- added title field to connections table for partners
- conditional rendering for partners needs to be accommodated by frontend

Partner + Exec interaction fixes + New Quests

---

services/interactions/helpers.js
services/interactions/serverless.yml

placed put item inside of booth handler

---

services/interactions/constants.js
services/interactions/helpers.js

Closes #
👷 **Changes:**
💭 **Notes:**

Merge master back to dev

---

services/interactions/helpers.js

Fix master

---

services/registrations/handler.js

Removing the registration blocker on BP 25 which was experiencing overfill - merging to prod

Revert BP 25 registrations block

---

constants/tables.js
lib/db.js
services/interactions/package-lock.json
services/teams/handler.js
services/teams/helpers.js
services/teams/serverless.yml

👷 **Changes:**
new endpoints to create update feedbacks, and add a team into judge entry

added put and post endpoints for bizJudge and bizFeedback

---

services/teams/constants.js
services/teams/handler.js
services/teams/helpers.js
services/teams/serverless.yml

- add index resources + scan
- add untracked weights file

ProductX Resource Access Changes and Bug Fixes

---

services/teams/handler.js
services/teams/serverless.yml

endpoint for FE display of team being judged

added currentTeam endpoint

---

services/teams/handler.js
services/teams/serverless.yml

changing path name and adding currentTeam name

currentTeam endpoint modification

---

services/teams/handler.js

[ProductX BE] fix getSubmissions response

---

services/teams/handler.js
services/teams/helpers.js

add teamName to response + prevent people from adding people in other teams

Product x judging

---

package.json
scripts/migratePartnerRegistrationsToJudges.js

Closes #
👷 **Changes:**
- Added migration script that copies all registrations where the flag isPartner === true into the judges table
💭 **Notes:**

ProductX Registrations -> Judges Migration script

---

services/bots/serverless.yml

will allow serverless to deploy

Remove unnecessary environment variable from yml

---

.github/workflows/deploy.yml

the main issue impacting deployment was a line in the yml file that was misconfigured, attempting to read from environment configurations instead of secrets.
I added the secrets to both workflows, (this time the correct deployment workflow), but how the secret is read does not have to be changed, it's already configured to work correctly

Fix Environment Issues for Slack Bot

---

.github/workflows/deploy-prod.yml
.github/workflows/deploy.yml
services/bots/handler.js
services/bots/helpers.js
services/bots/serverless.yml
services/teams/handler.js

👷 **Changes:**
added /summarize command to bot – grabs last ~100 msgs in channel, sends to OpenAI API, posts TLDR back
💭 **Notes:**
uses gpt-4o-mini so cheap af, safe to deploy, using my personal account

bot summarizer

---

services/bots/package-lock.json
services/bots/package.json

fix: add node-fetch dependancy

---

services/bots/helpers.js

non-ephemereal

---

services/bots/handler.js

makign it so that theres a pending message instead of an error

add pending message

---

services/bots/handler.js

Closes #
👷 **Changes:**
💭 **Notes:**

removed halt

---

services/bots/handler.js
services/bots/helpers.js

Added summarize for threads support

thread support

---

services/bots/handler.js
services/bots/helpers.js

Made sure to export the damn function

forgot to add export im dumb

---

services/bots/helpers.js

Updated prompt to make sure it mentions the user

updated prompt

---

services/bots/helpers.js

- Added Ali to slack-bot dev group
- Added bt-web-v2 and bizbot ping groups

add ali to devs in slack

---

services/bots/constants.js
services/bots/helpers.js

- added pings to project, benny merged last pr too fast

remove token log (lol) + slack pings

---

services/bots/package-lock.json

out of sync package lock -> merging to test if CD actually works

fix package lock?

---

package-lock.json
package.json

Testing CD again. Appears that discord bot development and expired cache meant package-lock.json was no longer in sync, making npm ci fail.

Fix membership cd

---

services/events/serverless.yml
services/hello/serverless.yml
services/interactions/serverless.yml
services/members/serverless.yml
services/prizes/serverless.yml
services/profiles/serverless.yml
services/qr/serverless.yml
services/registrations/serverless.yml
services/transactions/serverless.yml
services/users/serverless.yml

👷 **Changes:**
- add authorizer staging to export name
💭 **Notes:**
- should fix production deployment issues, enabling cloudformation to deploy separate authorizers for each environment

Authorizer Staging Hotfix

---

services/profiles/handler.js

For optimized profile pictures

optimized pfp handling

---

lib/db.js
scripts/registerDiscordCommand.js
services/bots/handlerDiscord.js
services/bots/handlerSlack.js
services/bots/helpersDiscord.js
services/bots/helpersSlack.js
services/interactions/handler.js
services/interactions/helpers.js
services/members/handler.js
services/payments/constants.js
services/payments/handler.js
services/profiles/handler.js
services/profiles/helpers.js
services/teams/helpers.js
services/users/handler.js

UBC student memberships -> $12.00, non students are $15.00
- no way to enforce whether a student marks themselves as a student or not but conditionally sets stripe price

Membership Pricing + Lint

---

services/bots/handlerDiscord.js
services/bots/helpersDiscord.js

No ticket but fixes bug
where helpers are not packaged by serverless when including file extension

Fix Module Imports for discord

---

.github/workflows/deploy.yml
.github/workflows/lint.yml
.github/workflows/test.yml
package-lock.json
package.json
services/bots/package-lock.json
services/bots/package.json
services/events/package-lock.json
services/hello/package-lock.json
services/interactions/package-lock.json
services/members/package-lock.json
services/payments/package-lock.json
services/prizes/package-lock.json
services/profiles/package-lock.json
services/qr/package-lock.json
services/registrations/package-lock.json
services/stickers/package-lock.json
services/teams/package-lock.json
services/transactions/package-lock.json
services/users/package-lock.json

lock serverless
